<?php
$data = array (
  0 => 
  array (
    'cat_id' => '14',
    'cat_name' => '首页底部文章',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '10',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '3',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '13',
    'cat_name' => '服务指南',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '20',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '1',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '19',
    'cat_name' => '信息披露',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '30',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '5',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  4 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  5 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  6 => 
  array (
    'cat_id' => '16',
    'cat_name' => '操作图示',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '22',
    'show_in_nav' => '0',
    'parent_id' => '13',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  7 => 
  array (
    'cat_id' => '15',
    'cat_name' => '关于我们',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '11',
    'show_in_nav' => '0',
    'parent_id' => '14',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  8 => 
  array (
    'cat_id' => '17',
    'cat_name' => '主要项目',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '12',
    'show_in_nav' => '0',
    'parent_id' => '14',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  9 => 
  array (
    'cat_id' => '18',
    'cat_name' => '其他',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '13',
    'show_in_nav' => '0',
    'parent_id' => '14',
    'has_children' => '0',
    'aricle_num' => '7',
  ),
  10 => 
  array (
    'cat_id' => '20',
    'cat_name' => '平台动态',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '31',
    'show_in_nav' => '0',
    'parent_id' => '19',
    'has_children' => '0',
    'aricle_num' => '9',
  ),
  11 => 
  array (
    'cat_id' => '21',
    'cat_name' => '产品公告',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '32',
    'show_in_nav' => '0',
    'parent_id' => '19',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  12 => 
  array (
    'cat_id' => '22',
    'cat_name' => '行业动态',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '33',
    'show_in_nav' => '0',
    'parent_id' => '19',
    'has_children' => '0',
    'aricle_num' => '51',
  ),
  13 => 
  array (
    'cat_id' => '23',
    'cat_name' => '媒体报道',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '34',
    'show_in_nav' => '0',
    'parent_id' => '19',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  14 => 
  array (
    'cat_id' => '29',
    'cat_name' => '理财资讯',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '19',
    'has_children' => '0',
    'aricle_num' => '46',
  ),
);
?>