<?php
$data = array (
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '理财频道',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '理财频道',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '余姚民生',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '9',
    'name' => '余姚民生',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '民生系列',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '6',
    'name' => '民生系列',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '雅安荥经系列',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '3',
    'name' => '雅安荥经系列',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '测试商品分类',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '7',
    'name' => '测试商品分类',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '新手包',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '1',
    'name' => '新手包',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '西南项目',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '25',
    'level' => 1,
    'id' => '8',
    'name' => '西南项目',
  ),
);
?>